### PR TITLE
Refactoring by splitting code into multiple files

### PR DESCRIPTION
**Pull request by jyliuu**
`randomPlantedForests.cpp` is now splitted into different files which are located in the `include` and `lib` directories under src. They contain the headers and class implementations respectively. In particular, the implementation for the classification rpf is now separate from rpf implementation used for regression.

### CODE REVIEW

**Review by jemus42 — CHANGES_REQUESTED** [review]
Thanks a lot!

Everything appears to still work as expected on the R side, aside from one test that I can't reproduce failing locally.

Only concern I have is that `WARNING` about the non-portable `Makefile`.

**Comment by jyliuu** [comment]
@jemus42 the portability issue seems to be fixed, but not sure about the test fail. I don't think that is due to my change.

**Comment by jyliuu** [comment]
> @jemus42 the portability issue seems to be fixed, but not sure about the test fail. I don't think that is due to my change.

Oddly enough, it seems that the test only fails for ubuntu. Perhaps this has something to do with the RNG?

**Comment by jemus42** [comment]
> > @jemus42 the portability issue seems to be fixed, but not sure about the test fail. I don't think that is due to my change.
> 
> Oddly enough, it seems that the test only fails for ubuntu. Perhaps this has something to do with the RNG?

Yes, I'll fix and/or remove that test after merging your PR - I don't see any way your changed would be related to that, and even that, that test is... not very sound in general 🥴 

Otherwise I think this is good to go, thanks a lot!
I'll shamelessly ignore Marvin and Munir and just merge this 😬

**Comment by mnwright** [comment]
Looks great!

**Pull request merged**
