### PR TITLE
Unify possible splits update logic + fix for rpf

### PR DESCRIPTION
**Pull request by jyliuu**
The check in the regression scenario for `curr_split.tree_index->split_dims.count(feature_dim) > 0)` is incorrect. 
Assume that we have the following tree growth:

1. Ø was split wrt 1, resulting in a {1}-tree, and potential splits now include ({1,2}, 2) and ({1,3}, 3)
2. {1} was split wrt. 2 resulting in a {1,2}-tree and potential splits now include ({1,2,3}, 3) but also ({1,2}, 1)

In the current code for the regression scenario, the ({1,2}, 1) option is not included after the second split. Classification does it correctly however.

### CODE REVIEW

**Review by jemus42 — APPROVED** [review]
I have not had the time to fully think through the algorithm in general so I'm happy just trusting you on this one 😅 

When it comes to the algorithm itself I'd let Munir and Joseph take the lead (not sure if either of them check their GitHub notifications on a regular basis).

**Comment by jyliuu** [comment]
> I have not had the time to fully think through the algorithm in general so I'm happy just trusting you on this one 😅
> 
> When it comes to the algorithm itself I'd let Munir and Joseph take the lead (not sure if either of them check their GitHub notifications on a regular basis).

I will just wait till they are back from holidays before merging :D

**Comment by MHiabu** [comment]
I tend to agree with @jyliuu. Can you check @JosephTMeyer?

**Comment by jemus42** [comment]
Any news here?

**Comment by jyliuu** [comment]
I merged it, pretty sure that it is correct.

**Pull request merged**
